#!/usr/bin/env ruby

# Pretty formats any json passed to it
#     cat file | jj
#     curl http://...json | jj
#     pbpaste | jj
#     echo '{"key":"value"}' | jj
#
# http://camdez.github.com/blog/2012/02/10/pretty-json-in-and-out-of-ruby/
#
# Can also use prettyjson node package for even better output
#
#     npm install prettyjson -g
#

require 'json'

jj JSON[ARGF.read]

